name: inv-nn-opt-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy=2.4.1
  - pandas=2.3.3
  - matplotlib=3.10.*
  - scipy=1.17.*
  - notebook=7.*
  - jupyterlab=4.*
  - ipykernel=7.1.*
  - pip=23.3.*

  - pip:
      - torch==2.9.*
      - torchvision==0.24.*
      - plotly==6.5.*
